version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    image: smodesto/nestapp:1.0.0
    environment:
      - DB_TYPE=${DB_TYPE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_HOST=${PG_HOST}

volumes:
  pgdata: {}
